DROP PROCEDURE IF EXISTS SP_FIND_ADMIN;
CREATE PROCEDURE SP_FIND_ADMIN(IN email VARCHAR(320), IN pwd VARCHAR(64))
SELECT * FROM ADMIN WHERE ADMIN.Email=email AND ADMIN.Password=pwd;

DROP PROCEDURE IF EXISTS SP_FIND_JUDGE;
CREATE PROCEDURE SP_FIND_JUDGE(IN email VARCHAR(320), IN pwd VARCHAR(64))
SELECT * FROM JUDGE WHERE JUDGE.Email=email AND JUDGE.Password=pwd;

DROP PROCEDURE IF EXISTS SP_COUNT_ADMIN;
CREATE PROCEDURE SP_COUNT_ADMIN(IN email VARCHAR(320), IN pwd VARCHAR(64))
SELECT COUNT(*) FROM ADMIN WHERE ADMIN.Email=email AND ADMIN.Password=pwd;

DROP PROCEDURE IF EXISTS SP_COUNT_JUDGE;
CREATE PROCEDURE SP_COUNT_JUDGE(IN email VARCHAR(320), IN pwd VARCHAR(64))
SELECT COUNT(*) FROM JUDGE WHERE JUDGE.Email=email AND JUDGE.Password=pwd;
